version: '3'

networks:
  backend:
    name: backend
    external: false

services:
  rpa-address-system:
    image: ${PROJECT_GROUP}:${PROJECT_NAME}
    container_name: ${PROJECT_NAME}
    restart: always
    tty: true
    hostname: ${HOSTNAME}
    environment:
      TZ: "Europe/Moscow"
      DEBUG: ${DEBUG}
    networks:
      - backend
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/rpa/data:/application/data
    labels:
      traefik.enable: true
      traefik.http.routers.rpa-address-system-web.entrypoints: websecure
      traefik.http.routers.rpa-address-system-web.rule: |
        Host(`${HOSTNAME}`)&& PathPrefix(`/admin`, `/static/admin`, `/api-auth`, `/gar`)
      traefik.http.routers.rpa-address-system-web.tls: true
      traefik.http.routers.rpa-address-system-web.service: rpa-address-system-web-service
      traefik.http.services.rpa-address-system-web-service.loadbalancer.server.port: 8000
