version: '3.6'

services:
  postgresql:
    image: 'postgres:13.8-alpine'
    container_name: postgresql
    restart: always
    environment:
      TZ: "Europe/Moscow"
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PWD}/data:/var/lib/postgresql/data
